import Navbar from "./components/navbar";
import "./globals.css";
import { Playfair } from "next/font/google";

const playfair = Playfair({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <Navbar />
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
